// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: 2432_1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenLogo
void ui_ScreenLogo_screen_init(void);
lv_obj_t * ui_ScreenLogo;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Image8;


// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
lv_obj_t * ui_ScreenMain;
lv_obj_t * ui_ImagePhoto;
lv_obj_t * ui_ImageName;
void ui_event_ibtnLogo(lv_event_t * e);
lv_obj_t * ui_ibtnLogo;
lv_obj_t * ui_ImageIn;
lv_obj_t * ui_ImageOut;
void ui_event_ibtnRoom(lv_event_t * e);
lv_obj_t * ui_ibtnRoom;


// SCREEN: ui_ScreenDevice
void ui_ScreenDevice_screen_init(void);
lv_obj_t * ui_ScreenDevice;
lv_obj_t * ui_Label16;
void ui_event_btnSaveID(lv_event_t * e);
lv_obj_t * ui_btnSaveID;
lv_obj_t * ui_Label19;
void ui_event_btnLoadMqtt(lv_event_t * e);
lv_obj_t * ui_btnLoadMqtt;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Label22;
void ui_event_btnLoadImages(lv_event_t * e);
lv_obj_t * ui_btnLoadImages;
lv_obj_t * ui_Label21;
void ui_event_ibtnWifi2(lv_event_t * e);
lv_obj_t * ui_ibtnWifi2;
void ui_event_btnReboot(lv_event_t * e);
lv_obj_t * ui_btnReboot;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Keyboard3;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label17;
void ui_event_txtaDeviceID(lv_event_t * e);
lv_obj_t * ui_txtaDeviceID;
lv_obj_t * ui_Label15;
void ui_event_txtaServerurl(lv_event_t * e);
lv_obj_t * ui_txtaServerurl;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Label25;
lv_obj_t * ui_dropSleep;
lv_obj_t * ui_Label26;
lv_obj_t * ui_dropReboot;
lv_obj_t * ui_Label27;


// SCREEN: ui_ScreenEthernet
void ui_ScreenEthernet_screen_init(void);
lv_obj_t * ui_ScreenEthernet;
lv_obj_t * ui_Label8;
void ui_event_ibtnWifi(lv_event_t * e);
lv_obj_t * ui_ibtnWifi;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label1;
void ui_event_chkDhcp(lv_event_t * e);
lv_obj_t * ui_chkDhcp;
void ui_event_txtaIp(lv_event_t * e);
lv_obj_t * ui_txtaIp;
void ui_event_txtaSubnet(lv_event_t * e);
lv_obj_t * ui_txtaSubnet;
void ui_event_txtaGateway(lv_event_t * e);
lv_obj_t * ui_txtaGateway;
void ui_event_txtaPriDns(lv_event_t * e);
lv_obj_t * ui_txtaPriDns;
void ui_event_txtaSeDns(lv_event_t * e);
lv_obj_t * ui_txtaSeDns;
void ui_event_btnEthernetConn(lv_event_t * e);
lv_obj_t * ui_btnEthernetConn;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Keyboard2;


// SCREEN: ui_ScreenWifi
void ui_ScreenWifi_screen_init(void);
lv_obj_t * ui_ScreenWifi;
lv_obj_t * ui_Label3;
lv_obj_t * ui_dropSSID;
void ui_event_txtaPassword(lv_event_t * e);
lv_obj_t * ui_txtaPassword;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
void ui_event_btnSerch(lv_event_t * e);
lv_obj_t * ui_btnSerch;
lv_obj_t * ui_Label6;
void ui_event_btnWifiConn(lv_event_t * e);
lv_obj_t * ui_btnWifiConn;
lv_obj_t * ui_Label7;
void ui_event_ibtnEthernet(lv_event_t * e);
lv_obj_t * ui_ibtnEthernet;
void ui_event_chkLookPass(lv_event_t * e);
lv_obj_t * ui_chkLookPass;
void ui_event_ibtnDevice(lv_event_t * e);
lv_obj_t * ui_ibtnDevice;
lv_obj_t * ui_Keyboard1;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_img[2] = {&ui_img_img01_png, &ui_img_img02_png};
const lv_img_dsc_t * ui_imgset_wifi[1] = {&ui_img_wifi2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ibtnLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ibtnLogo_Click(e);
    }
}
void ui_event_ibtnRoom(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ibtnRoom_Click(e);
    }
}
void ui_event_btnSaveID(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btnSaveID_Click(e);
    }
}
void ui_event_btnLoadMqtt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btnLoadMqtt_Click(e);
    }
}
void ui_event_btnLoadImages(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btnLoadImages_Click(e);
    }
}
void ui_event_ibtnWifi2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ibtnWifi_Click(e);
    }
}
void ui_event_btnReboot(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btnReboot_Click(e);
    }
}
void ui_event_txtaDeviceID(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        deviceInput_Focused(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        deviceInput_Defocused(e);
    }
}
void ui_event_txtaServerurl(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        deviceInput_Focused(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        deviceInput_Defocused(e);
    }
}
void ui_event_ibtnWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ibtnWifi_Click(e);
    }
}
void ui_event_chkDhcp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        chkDhcp_Checked(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        chkDhcp_Unchecked(e);
    }
}
void ui_event_txtaIp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        ethernetInput_Focused(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        ethernetInput_Defocused(e);
    }
}
void ui_event_txtaSubnet(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        ethernetInput_Focused(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        ethernetInput_Defocused(e);
    }
}
void ui_event_txtaGateway(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        ethernetInput_Focused(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        ethernetInput_Defocused(e);
    }
}
void ui_event_txtaPriDns(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        ethernetInput_Focused(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        ethernetInput_Defocused(e);
    }
}
void ui_event_txtaSeDns(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        ethernetInput_Focused(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        ethernetInput_Defocused(e);
    }
}
void ui_event_btnEthernetConn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btnEthernetConn_Click(e);
    }
}
void ui_event_txtaPassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        txtaPassword_Focused(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        txtaPassword_Defocused(e);
    }
}
void ui_event_btnSerch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btnSerch_Click(e);
    }
}
void ui_event_btnWifiConn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btnWifiConn_Click(e);
    }
}
void ui_event_ibtnEthernet(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ibtnEthernet_Click(e);
    }
}
void ui_event_chkLookPass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        chkLookPass_Checked(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        chkLookPass_Checked(e);
    }
}
void ui_event_ibtnDevice(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ibtnDevice_Click(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenLogo_screen_init();
    ui_ScreenMain_screen_init();
    ui_ScreenDevice_screen_init();
    ui_ScreenEthernet_screen_init();
    ui_ScreenWifi_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenLogo);
}
