// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: 2432_1

#ifndef _2432_1_UI_H
#define _2432_1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ScreenLogo
void ui_ScreenLogo_screen_init(void);
extern lv_obj_t * ui_ScreenLogo;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
extern lv_obj_t * ui_ScreenMain;
extern lv_obj_t * ui_ImagePhoto;
extern lv_obj_t * ui_ImageName;
void ui_event_ibtnLogo(lv_event_t * e);
extern lv_obj_t * ui_ibtnLogo;
extern lv_obj_t * ui_ImageIn;
extern lv_obj_t * ui_ImageOut;
void ui_event_ibtnRoom(lv_event_t * e);
extern lv_obj_t * ui_ibtnRoom;
// SCREEN: ui_ScreenDevice
void ui_ScreenDevice_screen_init(void);
extern lv_obj_t * ui_ScreenDevice;
extern lv_obj_t * ui_Label16;
void ui_event_btnSaveID(lv_event_t * e);
extern lv_obj_t * ui_btnSaveID;
extern lv_obj_t * ui_Label19;
void ui_event_btnLoadMqtt(lv_event_t * e);
extern lv_obj_t * ui_btnLoadMqtt;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label22;
void ui_event_btnLoadImages(lv_event_t * e);
extern lv_obj_t * ui_btnLoadImages;
extern lv_obj_t * ui_Label21;
void ui_event_ibtnWifi2(lv_event_t * e);
extern lv_obj_t * ui_ibtnWifi2;
void ui_event_btnReboot(lv_event_t * e);
extern lv_obj_t * ui_btnReboot;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Keyboard3;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label17;
void ui_event_txtaDeviceID(lv_event_t * e);
extern lv_obj_t * ui_txtaDeviceID;
extern lv_obj_t * ui_Label15;
void ui_event_txtaServerurl(lv_event_t * e);
extern lv_obj_t * ui_txtaServerurl;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_dropSleep;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_dropReboot;
extern lv_obj_t * ui_Label27;
// SCREEN: ui_ScreenEthernet
void ui_ScreenEthernet_screen_init(void);
extern lv_obj_t * ui_ScreenEthernet;
extern lv_obj_t * ui_Label8;
void ui_event_ibtnWifi(lv_event_t * e);
extern lv_obj_t * ui_ibtnWifi;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label1;
void ui_event_chkDhcp(lv_event_t * e);
extern lv_obj_t * ui_chkDhcp;
void ui_event_txtaIp(lv_event_t * e);
extern lv_obj_t * ui_txtaIp;
void ui_event_txtaSubnet(lv_event_t * e);
extern lv_obj_t * ui_txtaSubnet;
void ui_event_txtaGateway(lv_event_t * e);
extern lv_obj_t * ui_txtaGateway;
void ui_event_txtaPriDns(lv_event_t * e);
extern lv_obj_t * ui_txtaPriDns;
void ui_event_txtaSeDns(lv_event_t * e);
extern lv_obj_t * ui_txtaSeDns;
void ui_event_btnEthernetConn(lv_event_t * e);
extern lv_obj_t * ui_btnEthernetConn;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Keyboard2;
// SCREEN: ui_ScreenWifi
void ui_ScreenWifi_screen_init(void);
extern lv_obj_t * ui_ScreenWifi;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_dropSSID;
void ui_event_txtaPassword(lv_event_t * e);
extern lv_obj_t * ui_txtaPassword;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
void ui_event_btnSerch(lv_event_t * e);
extern lv_obj_t * ui_btnSerch;
extern lv_obj_t * ui_Label6;
void ui_event_btnWifiConn(lv_event_t * e);
extern lv_obj_t * ui_btnWifiConn;
extern lv_obj_t * ui_Label7;
void ui_event_ibtnEthernet(lv_event_t * e);
extern lv_obj_t * ui_ibtnEthernet;
void ui_event_chkLookPass(lv_event_t * e);
extern lv_obj_t * ui_chkLookPass;
void ui_event_ibtnDevice(lv_event_t * e);
extern lv_obj_t * ui_ibtnDevice;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_logo_png);    // assets\logo.png
LV_IMG_DECLARE(ui_img_img01_png);    // assets\img01.png
LV_IMG_DECLARE(ui_img_img02_png);    // assets\img02.png
LV_IMG_DECLARE(ui_img_photo_png);    // assets\photo.png
LV_IMG_DECLARE(ui_img_name_png);    // assets\name.png
LV_IMG_DECLARE(ui_img_title_png);    // assets\title.png
LV_IMG_DECLARE(ui_img_in_png);    // assets\in.png
LV_IMG_DECLARE(ui_img_out_png);    // assets\out.png
LV_IMG_DECLARE(ui_img_ethernet_png);    // assets\ethernet.png
LV_IMG_DECLARE(ui_img_set_png);    // assets\set.png
LV_IMG_DECLARE(ui_img_wifi2_png);    // assets\wifi2.png

LV_FONT_DECLARE(ui_font_nanumB15);
LV_FONT_DECLARE(ui_font_nanumB20);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
