// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: 2432_1

#include "ui.h"

void ibtnLogo_Click(lv_event_t * e)
{
	// Your code here
}

void ibtnRoom_Click(lv_event_t * e)
{
	// Your code here
}

void btnSaveID_Click(lv_event_t * e)
{
	// Your code here
}

void btnLoadMqtt_Click(lv_event_t * e)
{
	// Your code here
}

void btnLoadImages_Click(lv_event_t * e)
{
	// Your code here
}

void ibtnWifi_Click(lv_event_t * e)
{
	// Your code here
}

void btnReboot_Click(lv_event_t * e)
{
	// Your code here
}

void deviceInput_Focused(lv_event_t * e)
{
	// Your code here
}

void deviceInput_Defocused(lv_event_t * e)
{
	// Your code here
}

void chkDhcp_Checked(lv_event_t * e)
{
	// Your code here
}

void chkDhcp_Unchecked(lv_event_t * e)
{
	// Your code here
}

void ethernetInput_Focused(lv_event_t * e)
{
	// Your code here
}

void ethernetInput_Defocused(lv_event_t * e)
{
	// Your code here
}

void btnEthernetConn_Click(lv_event_t * e)
{
	// Your code here
}

void txtaPassword_Focused(lv_event_t * e)
{
	// Your code here
}

void txtaPassword_Defocused(lv_event_t * e)
{
	// Your code here
}

void btnSerch_Click(lv_event_t * e)
{
	// Your code here
}

void btnWifiConn_Click(lv_event_t * e)
{
	// Your code here
}

void ibtnEthernet_Click(lv_event_t * e)
{
	// Your code here
}

void chkLookPass_Checked(lv_event_t * e)
{
	// Your code here
}

void ibtnDevice_Click(lv_event_t * e)
{
	// Your code here
}
