// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: 2432_1

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ibtnLogo_Click(lv_event_t * e);
void ibtnRoom_Click(lv_event_t * e);
void btnSaveID_Click(lv_event_t * e);
void btnLoadMqtt_Click(lv_event_t * e);
void btnLoadImages_Click(lv_event_t * e);
void ibtnWifi_Click(lv_event_t * e);
void btnReboot_Click(lv_event_t * e);
void deviceInput_Focused(lv_event_t * e);
void deviceInput_Defocused(lv_event_t * e);
void chkDhcp_Checked(lv_event_t * e);
void chkDhcp_Unchecked(lv_event_t * e);
void ethernetInput_Focused(lv_event_t * e);
void ethernetInput_Defocused(lv_event_t * e);
void btnEthernetConn_Click(lv_event_t * e);
void txtaPassword_Focused(lv_event_t * e);
void txtaPassword_Defocused(lv_event_t * e);
void btnSerch_Click(lv_event_t * e);
void btnWifiConn_Click(lv_event_t * e);
void ibtnEthernet_Click(lv_event_t * e);
void chkLookPass_Checked(lv_event_t * e);
void ibtnDevice_Click(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
