// Auto-generated by tools/embed_www.py — DO NOT EDIT
// data/www/* → PROGMEM (SPIFFS 미터치, 펌웨어/UI 버전 일관성)
#include "embedded_assets.h"

const char INDEX_HTML[] PROGMEM = R"RDT(<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>RemoteDeck_Touch · Web UI</title>
<link rel="stylesheet" href="/style.css">
</head>
<body>
<header>
  <h1>RemoteDeck_Touch</h1>
  <span id="statusBar">loading...</span>
</header>

<nav class="tabs">
  <button class="tab active" data-tab="control">Control</button>
  <button class="tab" data-tab="images">Images</button>
  <button class="tab" data-tab="config">Config</button>
  <button class="tab" data-tab="logs">Logs</button>
</nav>

<main>
  <!-- Control Tab -->
  <section class="tab-panel active" id="tab-control">
    <div class="card">
      <h2>현재 상태</h2>
      <div class="ctrl-status">
        <div class="ctrl-indicator" id="ctrlIndicator">
          <div class="state-circle" id="ctrlCircle"></div>
          <div class="state-label" id="ctrlLabel">—</div>
        </div>
        <div class="ctrl-meta">
          <div>etag: <span id="ctrlEtag">0</span></div>
          <div>polling: <span id="ctrlPolling">idle</span></div>
        </div>
      </div>
    </div>
    <div class="card">
      <h2>토글</h2>
      <div class="ctrl-buttons">
        <button id="btnIn" class="ctrl-btn ctrl-in">재실 (IN)</button>
        <button id="btnOut" class="ctrl-btn ctrl-out">부재 (OUT)</button>
      </div>
      <p class="hint">버튼 클릭 시 MQTT room/client 토픽으로 publish + LCD 동기 미러.</p>
    </div>
  </section>

  <!-- Images Tab -->
  <section class="tab-panel" id="tab-images">
    <div class="card">
      <h2>현재 이미지</h2>
      <div class="card-row" id="imageCards"><!-- JS --></div>
    </div>
    <div class="card">
      <h2>업로드</h2>
      <div id="dropZone" class="drop-zone">
        <p>PNG 또는 BMP 파일을 여기에 드래그&드롭<br>또는</p>
        <input type="file" id="fileInput" accept=".png,.bmp">
      </div>
      <div class="progress-bar" id="progressBar" hidden>
        <div class="progress-fill" id="progressFill">0%</div>
      </div>
    </div>
  </section>

  <!-- Config Tab -->
  <section class="tab-panel" id="tab-config">
    <div class="card">
      <h2>Device Config (JSON)</h2>
      <textarea id="configEditor" class="config-editor" spellcheck="false" rows="20"></textarea>
      <div class="btn-row">
        <button id="cfgReload">불러오기</button>
        <button id="cfgSave" class="primary">저장</button>
        <button id="cfgReboot" class="danger">재부팅</button>
      </div>
      <div id="cfgMsg" class="hint">deviceconfig.json 을 직접 편집합니다. 저장 후 반영을 위해 재부팅이 필요할 수 있습니다.</div>
    </div>
    <div class="card">
      <h2>Images Config (read-only)</h2>
      <pre id="imagesConfigView" class="config-view">loading...</pre>
    </div>
    <div class="card">
      <h2>OTA 펌웨어 업데이트</h2>
      <p class="hint">PIO 빌드의 OTA bin (firmware.bin, 1.7MB 내외) 선택. 업로드 완료 후 자동 재부팅.</p>
      <input type="file" id="otaFile" accept=".bin">
      <button id="otaUpload" class="primary">OTA 업로드</button>
      <div class="progress-bar" id="otaProgress" hidden>
        <div class="progress-fill" id="otaFill">0%</div>
      </div>
      <div id="otaMsg" class="hint"></div>
    </div>
  </section>

  <!-- Logs Tab -->
  <section class="tab-panel" id="tab-logs">
    <div class="card">
      <h2>Server Log (ring buffer 50)</h2>
      <div class="btn-row">
        <button id="logRefresh">새로고침</button>
        <label class="toggle"><input type="checkbox" id="logAuto"> 10초 자동 새로고침</label>
      </div>
      <div class="log-container" id="serverLog">loading...</div>
    </div>
  </section>
</main>

<div id="toast" class="toast" hidden></div>
<script src="/app.js"></script>
</body>
</html>
)RDT";

const char STYLE_CSS[] PROGMEM = R"RDT(/* RemoteDeck_Touch web UI · PC 디자인 토큰 + tab 추가 */
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:system-ui,-apple-system,sans-serif;background:#1a1a2e;color:#e0e0e0;font-size:14px;min-height:100vh}
header{background:#16213e;padding:12px 20px;display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:8px}
header h1{font-size:18px;color:#0ff;font-weight:bold}
header span{font-size:12px;color:#888;font-family:monospace}

nav.tabs{background:#0f1830;padding:0 12px;display:flex;gap:2px;border-bottom:1px solid #2a3050}
.tab{background:transparent;border:none;color:#888;padding:12px 18px;cursor:pointer;font-size:13px;border-bottom:2px solid transparent;transition:all .15s}
.tab:hover{color:#0ff}
.tab.active{color:#0ff;border-bottom-color:#0ff}

main{padding:12px;max-width:900px;margin:0 auto}
.tab-panel{display:none}
.tab-panel.active{display:block}

.card{background:#16213e;border-radius:8px;padding:16px;margin-bottom:12px}
.card h2{font-size:14px;color:#0ff;margin-bottom:12px;border-bottom:1px solid #333;padding-bottom:6px}

.card-row{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}
.img-card{background:#0a0e27;border-radius:6px;padding:12px;border:1px solid #2a3050}
.img-card .role{font-size:12px;color:#0ff;font-weight:bold;text-transform:uppercase;margin-bottom:6px}
.img-card .thumb{background:#000;border-radius:4px;height:80px;display:flex;align-items:center;justify-content:center;overflow:hidden;margin-bottom:8px}
.img-card .thumb img{max-width:100%;max-height:100%;object-fit:contain}
.img-card .thumb .placeholder{color:#444;font-size:11px}
.img-card .meta{font-size:11px;color:#888;margin-bottom:8px;font-family:monospace}
.img-card button{width:100%;padding:6px 12px;background:#0f3460;border:1px solid #0ff;color:#0ff;border-radius:4px;cursor:pointer;font-size:12px}
.img-card button:hover{background:#1a5276}
.img-card button.danger{border-color:#f44;color:#f44;margin-top:4px}
.img-card button.danger:hover{background:#3a1a1a}

.drop-zone{border:2px dashed #2a3050;border-radius:8px;padding:24px;text-align:center;color:#aaa;transition:all .2s}
.drop-zone.dragover{border-color:#0ff;background:#0f3460;color:#0ff}
.drop-zone p{margin-bottom:8px;line-height:1.5}
.drop-zone input[type="file"]{margin:8px auto;color:#aaa}

.progress-bar{background:#0a0e27;border-radius:4px;height:20px;margin:10px 0;overflow:hidden;border:1px solid #2a3050}
.progress-fill{background:linear-gradient(90deg,#0ff,#0a8);height:100%;width:0%;transition:width .3s;color:#000;text-align:center;font-size:12px;font-weight:bold;line-height:20px}

/* Config tab */
.config-editor{width:100%;background:#0a0e27;color:#e0e0e0;border:1px solid #2a3050;border-radius:4px;padding:10px;font-family:monospace;font-size:12px;line-height:1.4;resize:vertical;min-height:280px}
.config-view{background:#0a0e27;color:#bbb;border:1px solid #2a3050;border-radius:4px;padding:10px;font-family:monospace;font-size:12px;white-space:pre-wrap;max-height:280px;overflow:auto}
.btn-row{display:flex;gap:8px;margin-top:8px;flex-wrap:wrap;align-items:center}
.btn-row button{padding:8px 16px;background:#0f3460;border:1px solid #0ff;color:#0ff;border-radius:4px;cursor:pointer;font-size:12px}
.btn-row button:hover{background:#1a5276}
.btn-row button.primary{background:#0ff;color:#000}
.btn-row button.primary:hover{background:#0dd}
.btn-row button.danger{border-color:#f44;color:#f44;background:transparent}
.btn-row button.danger:hover{background:#3a1a1a}
.btn-row .toggle{color:#aaa;font-size:12px;display:flex;align-items:center;gap:6px;margin-left:auto}
.hint{margin-top:8px;color:#777;font-size:11px}

/* Logs tab */
.log-container{max-height:400px;overflow-y:auto;font-family:monospace;font-size:12px;background:#0a0e27;border:1px solid #2a3050;border-radius:4px;padding:8px;margin-top:8px}
.log-entry{padding:4px 0;border-bottom:1px solid #222}
.log-entry .time{color:#888;margin-right:8px}
.log-entry .event{color:#0ff;margin-right:8px;font-weight:bold}
.log-entry.ok .event{color:#0f0}
.log-entry.fail .event{color:#f44}

.toast{position:fixed;bottom:24px;left:50%;transform:translateX(-50%);background:#16213e;border:1px solid #0ff;color:#0ff;padding:12px 20px;border-radius:6px;font-size:13px;z-index:1000;box-shadow:0 4px 12px rgba(0,0,0,.4);max-width:90%}
.toast.fail{border-color:#f44;color:#f44}

/* Control tab */
.ctrl-status{display:flex;align-items:center;gap:24px;flex-wrap:wrap}
.ctrl-indicator{display:flex;align-items:center;gap:14px;flex:1}
.state-circle{width:48px;height:48px;border-radius:50%;background:#333;border:2px solid #555;transition:all .3s}
.state-circle.in{background:#0a8;border-color:#0fa;box-shadow:0 0 20px #0fa}
.state-circle.out{background:#a40;border-color:#fa0;box-shadow:0 0 20px #fa0}
.state-label{font-size:20px;font-weight:bold;color:#888}
.state-label.in{color:#0fa}
.state-label.out{color:#fa0}
.ctrl-meta{color:#888;font-size:12px;font-family:monospace;display:flex;flex-direction:column;gap:4px}
.ctrl-buttons{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.ctrl-btn{padding:24px;font-size:18px;font-weight:bold;border-radius:8px;cursor:pointer;background:#0a0e27;border:2px solid #2a3050;color:#aaa;transition:all .15s}
.ctrl-btn:hover{transform:translateY(-2px)}
.ctrl-btn.ctrl-in{border-color:#0fa;color:#0fa}
.ctrl-btn.ctrl-in:hover,.ctrl-btn.ctrl-in.active{background:#0a8;color:#000}
.ctrl-btn.ctrl-out{border-color:#fa0;color:#fa0}
.ctrl-btn.ctrl-out:hover,.ctrl-btn.ctrl-out.active{background:#a40;color:#fff}
)RDT";

const char APP_JS[] PROGMEM = R"RDT(// RemoteDeck_Touch · Web UI (module-webui: Images + Config + Logs)
// Design Ref: §5.1, §5.4

const $ = id => document.getElementById(id);
const ROLES = ['title', 'photo', 'name'];
const fmtBytes = n => n < 1024 ? n + 'B' : n < 1048576 ? (n/1024).toFixed(1)+'KB' : (n/1048576).toFixed(2)+'MB';
const fmtMs = ms => { const s = Math.floor(ms/1000); return new Date(s*1000).toTimeString().slice(0,8); };

// ---------- Tabs ----------
function activateTab(name) {
  document.querySelectorAll('.tab').forEach(b => b.classList.toggle('active', b.dataset.tab === name));
  document.querySelectorAll('.tab-panel').forEach(p => p.classList.toggle('active', p.id === 'tab-' + name));
  if (name === 'config' && !configLoaded) loadConfig();
  if (name === 'logs') refreshLog();
}

// ---------- Control Tab (Long polling 10s + ETag) ----------
let ctrlEtag = 0;
let ctrlPolling = false;
let ctrlAbort = null;

function renderCtrl(d) {
  const circle = $('ctrlCircle'), label = $('ctrlLabel');
  const btnIn = $('btnIn'), btnOut = $('btnOut');
  circle.className = 'state-circle' + (d.in ? ' in' : d.out ? ' out' : '');
  label.className = 'state-label' + (d.in ? ' in' : d.out ? ' out' : '');
  label.textContent = d.in ? '재실 (IN)' : d.out ? '부재 (OUT)' : '대기';
  btnIn.classList.toggle('active', d.in);
  btnOut.classList.toggle('active', d.out);
  $('ctrlEtag').textContent = d.etag;
}

async function pollControl() {
  if (ctrlPolling) return;
  ctrlPolling = true;
  $('ctrlPolling').textContent = 'polling…';
  while (ctrlPolling) {
    try {
      ctrlAbort = new AbortController();
      const r = await fetch(`/api/control?since=${ctrlEtag}`, { signal: ctrlAbort.signal });
      if (!r.ok) throw new Error('HTTP ' + r.status);
      const d = await r.json();
      ctrlEtag = d.etag;
      renderCtrl(d);
    } catch (e) {
      if (e.name === 'AbortError') break;
      $('ctrlPolling').textContent = 'error: ' + e.message;
    }
    // 3초 throttle — esp_http_server max_open_sockets=4 한계 압박 회피
    await new Promise(r => setTimeout(r, 3000));
  }
  $('ctrlPolling').textContent = 'idle';
}

function stopPolling() {
  ctrlPolling = false;
  if (ctrlAbort) ctrlAbort.abort();
}

async function toggleControl(state) {
  // state: 'in' or 'out'
  const body = state === 'in' ? { in: true } : { out: true };
  try {
    const r = await fetch('/api/control', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body)
    });
    if (!r.ok) throw new Error('HTTP ' + r.status);
    const d = await r.json();
    ctrlEtag = d.etag;
    renderCtrl(d);
    toast(`${state.toUpperCase()} 전송됨 (etag=${d.etag})`);
  } catch (e) {
    toast('전송 실패: ' + e.message, true);
  }
}

// ---------- Status ----------
async function fetchStatus() {
  try {
    const r = await fetch('/api/status');
    if (!r.ok) throw new Error('HTTP ' + r.status);
    const s = await r.json();
    $('statusBar').textContent =
      `heap=${fmtBytes(s.heap_free)} (min ${fmtBytes(s.heap_min)}) · ` +
      `spiffs=${fmtBytes(s.spiffs_used)}/${fmtBytes(s.spiffs_total)} · ` +
      `${s.network.iface} ${s.network.ip} · v${s.fw_version}`;
  } catch (e) {
    $('statusBar').textContent = 'status error: ' + e.message;
  }
}

// ---------- Toast ----------
function toast(msg, fail = false, ms = 3000) {
  const t = $('toast');
  t.textContent = msg;
  t.className = 'toast' + (fail ? ' fail' : '');
  t.hidden = false;
  clearTimeout(toast._t);
  toast._t = setTimeout(() => { t.hidden = true; }, ms);
}

// ---------- Images Tab ----------
async function fetchImagesList() {
  try {
    const r = await fetch('/api/images/list');
    if (!r.ok) throw new Error('HTTP ' + r.status);
    return await r.json();
  } catch (e) {
    toast('이미지 목록 로드 실패: ' + e.message, true);
    return { images: [] };
  }
}

function matchImageForRole(images, role) {
  return images.find(i => i.name.toLowerCase() === role + '.png')
      || images.find(i => i.name.toLowerCase() === role + '.bmp');
}

async function renderImageCards() {
  const data = await fetchImagesList();
  const cards = ROLES.map(role => {
    const img = matchImageForRole(data.images, role);
    const cacheBust = '?t=' + Date.now();
    const thumb = img
      ? `<img src="/api/images/${img.name}${cacheBust}" alt="${role}">`
      : `<div class="placeholder">no image</div>`;
    const meta = img ? `${img.name} · ${fmtBytes(img.size)}` : '— 기본 이미지 사용 —';
    const del = img ? `<button class="danger" data-del="${img.name}">삭제</button>` : '';
    return `
      <div class="img-card">
        <div class="role">${role}</div>
        <div class="thumb">${thumb}</div>
        <div class="meta">${meta}</div>
        <button data-role="${role}">교체</button>
        ${del}
      </div>`;
  }).join('');
  $('imageCards').innerHTML = cards;
  $('imageCards').querySelectorAll('button[data-role]').forEach(b =>
    b.onclick = () => triggerFileSelect(b.dataset.role));
  $('imageCards').querySelectorAll('button[data-del]').forEach(b =>
    b.onclick = () => deleteImage(b.dataset.del));
}

function triggerFileSelect(role) {
  const inp = $('fileInput');
  inp.dataset.targetRole = role;
  inp.click();
}

async function uploadFile(file) {
  if (!file) return;
  const name = file.name.toLowerCase();
  if (!name.endsWith('.png') && !name.endsWith('.bmp')) {
    toast('PNG 또는 BMP 파일만 업로드 가능', true);
    return;
  }
  if (file.size > 200 * 1024) {
    toast(`파일이 너무 큼: ${fmtBytes(file.size)} (최대 200KB)`, true);
    return;
  }
  const role = $('fileInput').dataset.targetRole;
  const ext = name.endsWith('.png') ? '.png' : '.bmp';
  const finalName = role ? (role + ext) : file.name;
  const renamed = new File([file], finalName, { type: file.type });
  const fd = new FormData();
  fd.append('file', renamed);

  const bar = $('progressBar'), fill = $('progressFill');
  bar.hidden = false; fill.style.width = '0%'; fill.textContent = '0%';

  try {
    await new Promise((resolve, reject) => {
      const xhr = new XMLHttpRequest();
      xhr.open('POST', '/api/images/upload');
      xhr.upload.onprogress = e => {
        if (e.lengthComputable) {
          const p = Math.round(e.loaded * 100 / e.total);
          fill.style.width = p + '%'; fill.textContent = p + '%';
        }
      };
      xhr.onload = () => xhr.status >= 200 && xhr.status < 300 ? resolve() : reject(new Error('HTTP ' + xhr.status));
      xhr.onerror = () => reject(new Error('network'));
      xhr.send(fd);
    });
    toast(`${finalName} 업로드 완료 — 단말 갱신 중`);
    setTimeout(renderImageCards, 1500);
  } catch (e) {
    toast(`업로드 실패: ${e.message}`, true);
  } finally {
    setTimeout(() => { bar.hidden = true; }, 1500);
    $('fileInput').dataset.targetRole = '';
    $('fileInput').value = '';
  }
}

async function deleteImage(name) {
  if (!confirm(`${name} 을(를) 삭제하시겠습니까?`)) return;
  try {
    const r = await fetch('/api/images/' + name, { method: 'DELETE' });
    if (!r.ok) throw new Error('HTTP ' + r.status);
    toast(`${name} 삭제됨`);
    setTimeout(renderImageCards, 800);
  } catch (e) {
    toast(`삭제 실패: ${e.message}`, true);
  }
}

function bindDragDrop() {
  const z = $('dropZone');
  ['dragenter', 'dragover'].forEach(ev => z.addEventListener(ev, e => { e.preventDefault(); z.classList.add('dragover'); }));
  ['dragleave', 'drop'].forEach(ev => z.addEventListener(ev, e => { e.preventDefault(); z.classList.remove('dragover'); }));
  z.addEventListener('drop', e => { const f = e.dataTransfer.files[0]; if (f) uploadFile(f); });
  $('fileInput').addEventListener('change', e => { if (e.target.files[0]) uploadFile(e.target.files[0]); });
}

// ---------- Config Tab ----------
let configLoaded = false;

async function loadConfig() {
  try {
    const r = await fetch('/api/config');
    if (!r.ok) throw new Error('HTTP ' + r.status);
    const txt = await r.text();
    let pretty = txt;
    try { pretty = JSON.stringify(JSON.parse(txt), null, 2); } catch (_) { /* keep raw */ }
    $('configEditor').value = pretty;
    configLoaded = true;
  } catch (e) {
    $('configEditor').value = '// load failed: ' + e.message;
  }
  // imagesconfig.json (read-only)
  try {
    const r = await fetch('/api/imagesconfig');
    const txt = await r.text();
    let pretty = txt; try { pretty = JSON.stringify(JSON.parse(txt), null, 2); } catch (_) {}
    $('imagesConfigView').textContent = pretty;
  } catch (e) {
    $('imagesConfigView').textContent = 'load failed';
  }
}

async function saveConfig() {
  const body = $('configEditor').value;
  // 클라이언트 사이드 JSON 검증
  try { JSON.parse(body); } catch (e) {
    toast('JSON 형식 오류: ' + e.message, true); return;
  }
  try {
    const r = await fetch('/api/config', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body
    });
    if (!r.ok) {
      const e = await r.text();
      throw new Error(e || 'HTTP ' + r.status);
    }
    toast('설정 저장됨 (재부팅 후 반영)');
  } catch (e) {
    toast('저장 실패: ' + e.message, true);
  }
}

async function uploadOta() {
  const f = $('otaFile').files[0];
  if (!f) { toast('OTA bin 파일을 선택하세요', true); return; }
  if (!f.name.toLowerCase().endsWith('.bin')) {
    toast('.bin 파일만 업로드 가능', true); return;
  }
  if (f.size > 1900 * 1024) {
    toast(`파일 크기 초과: ${(f.size/1024).toFixed(0)}KB (최대 ~1.85MB)`, true); return;
  }
  if (!confirm(`${f.name} (${(f.size/1024).toFixed(0)}KB) 업로드 후 자동 재부팅됩니다. 진행하시겠습니까?`)) return;

  const fd = new FormData();
  fd.append('file', f);
  const bar = $('otaProgress'), fill = $('otaFill'), msg = $('otaMsg');
  bar.hidden = false; fill.style.width = '0%'; fill.textContent = '0%';
  msg.textContent = '업로드 중...';

  try {
    await new Promise((resolve, reject) => {
      const xhr = new XMLHttpRequest();
      xhr.open('POST', '/api/ota');
      xhr.timeout = 120000;  // OTA 는 시간 걸림
      xhr.upload.onprogress = e => {
        if (e.lengthComputable) {
          const p = Math.round(e.loaded * 100 / e.total);
          fill.style.width = p + '%'; fill.textContent = p + '%';
        }
      };
      xhr.onload = () => xhr.status >= 200 && xhr.status < 300 ? resolve() : reject(new Error('HTTP ' + xhr.status));
      xhr.onerror = () => reject(new Error('network'));
      xhr.ontimeout = () => reject(new Error('timeout'));
      xhr.send(fd);
    });
    msg.textContent = '✅ 업로드 완료 — 단말 재부팅 중 (~20초 대기)';
    toast('OTA 성공 — 재부팅 중');
  } catch (e) {
    // 단말이 OTA 성공 후 응답 send 도중 reboot → connection drop = network/timeout.
    // 단순 fail 보다는 reboot 가능성 안내 (사용자가 새로고침으로 확인).
    msg.textContent = '⚠ 응답 끊김 (' + e.message + ') — 단말 reboot 중일 수 있음. 30초 대기 후 새로고침';
    toast('연결 끊김 — 단말 reboot 가능성, 30초 대기 후 확인', false, 5000);
    setTimeout(() => { window.location.reload(); }, 30000);
  }
}

async function rebootDevice() {
  if (!confirm('지금 재부팅하시겠습니까? 약 15-30초 후 다시 접속 가능합니다.')) return;
  try {
    const r = await fetch('/api/reboot', { method: 'POST' });
    if (r.ok) toast('재부팅 중...');
  } catch (e) {
    toast('재부팅 요청 실패: ' + e.message, true);
  }
}

// ---------- Logs Tab ----------
let logAutoInterval = null;

async function refreshLog() {
  try {
    const r = await fetch('/api/log');
    if (!r.ok) throw new Error('HTTP ' + r.status);
    const d = await r.json();
    const html = (d.entries || []).map(e => `
      <div class="log-entry ok">
        <span class="time">${fmtMs(e.ts)}</span>
        <span class="event">${e.event}</span>
        ${e.detail}
      </div>`).join('') || '<div class="hint">no entries</div>';
    $('serverLog').innerHTML = html;
  } catch (e) {
    $('serverLog').textContent = 'log fetch failed: ' + e.message;
  }
}

function toggleLogAuto() {
  if ($('logAuto').checked) {
    refreshLog();
    logAutoInterval = setInterval(refreshLog, 10000);  // 10s
  } else {
    if (logAutoInterval) { clearInterval(logAutoInterval); logAutoInterval = null; }
  }
}

// ---------- Init ----------
async function init() {
  // tabs
  document.querySelectorAll('.tab').forEach(b =>
    b.addEventListener('click', () => activateTab(b.dataset.tab)));
  // images
  bindDragDrop();
  await renderImageCards();
  // config buttons
  $('cfgReload').addEventListener('click', loadConfig);
  $('cfgSave').addEventListener('click', saveConfig);
  $('cfgReboot').addEventListener('click', rebootDevice);
  $('otaUpload').addEventListener('click', uploadOta);
  // log buttons
  $('logRefresh').addEventListener('click', refreshLog);
  $('logAuto').addEventListener('change', toggleLogAuto);
  // control buttons + long polling 시작
  $('btnIn').addEventListener('click', () => toggleControl('in'));
  $('btnOut').addEventListener('click', () => toggleControl('out'));
  pollControl();  // 페이지 로딩 시 즉시 시작 (Control 탭 기본 활성)
  // status — 5초 폴링 (이미지 탭 외에도 항상)
  await fetchStatus();
  setInterval(fetchStatus, 5000);
}

init();
)RDT";
