#!/usr/bin/env python3
# data/www/{index.html,style.css,app.js} → src/web/embedded_assets.cpp 자동 생성
# PROGMEM raw string literal — 빌드 시점에 sync 보장.
# 실행: python tools/embed_www.py

import os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, "data", "www")
OUT  = os.path.join(ROOT, "src", "web", "embedded_assets.cpp")

ASSETS = [("INDEX_HTML", "index.html"),
          ("STYLE_CSS",  "style.css"),
          ("APP_JS",     "app.js")]

DELIM = "RDT"

def read(name):
    with open(os.path.join(SRC, name), "r", encoding="utf-8") as f:
        return f.read()

def main():
    parts = ["// Auto-generated by tools/embed_www.py — DO NOT EDIT",
             "// data/www/* → PROGMEM (SPIFFS 미터치, 펌웨어/UI 버전 일관성)",
             "#include \"embedded_assets.h\"",
             ""]
    for sym, fname in ASSETS:
        content = read(fname)
        # raw string delimiter 충돌 검사
        if (f')%s"' % DELIM) in content:
            print(f"ERROR: delimiter ')%s\"' clashes with {fname}" % DELIM, file=sys.stderr)
            sys.exit(2)
        parts.append(f"const char {sym}[] PROGMEM = R\"{DELIM}({content}){DELIM}\";")
        parts.append("")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(parts))
    print(f"wrote {OUT} ({sum(os.path.getsize(os.path.join(SRC,fn)) for _,fn in ASSETS)} bytes total)")

if __name__ == "__main__":
    main()
