#!/usr/bin/env python3
# data/www/{index.html,style.css,app.js} → src/web/embedded_assets.cpp 생성
# v2.3-final-gz: gzip 사전 압축으로 22KB → ~6KB. ESP32 의 TCP send 부담 ↓.
#   - INDEX_HTML_GZ: inline HTML (CSS+JS 통합) 을 gzip 압축한 bytes array
#   - 응답 시 Content-Encoding: gzip 헤더 + 단일 httpd_resp_send

import os, sys, gzip, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, "data", "www")
OUT  = os.path.join(ROOT, "src", "web", "embedded_assets.cpp")

def read(name):
    with open(os.path.join(SRC, name), "r", encoding="utf-8") as f:
        return f.read()

def build_inline_html(html, css, js):
    css_block = f"<style>\n{css}\n</style>"
    html = re.sub(r'<link[^>]*rel=["\']stylesheet["\'][^>]*>', css_block, html, count=1)
    js_block = f"<script>\n{js}\n</script>"
    html = re.sub(r'<script\s+src=["\']/app\.js["\']\s*></script>', js_block, html, count=1)
    return html

def to_byte_array_cpp(sym, data):
    """Generate `const uint8_t SYM[] PROGMEM = { 0x.., ... };` + SYM_LEN constant."""
    lines = [f"const uint8_t {sym}[] PROGMEM = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"const size_t {sym}_LEN = {len(data)};")
    return "\n".join(lines)

def main():
    html_raw = read("index.html")
    css_raw  = read("style.css")
    js_raw   = read("app.js")

    inline_html = build_inline_html(html_raw, css_raw, js_raw)
    inline_bytes = inline_html.encode("utf-8")
    gz = gzip.compress(inline_bytes, compresslevel=9)

    print(f"  inline HTML raw: {len(inline_bytes):,} bytes")
    print(f"  gzip compressed: {len(gz):,} bytes ({100*len(gz)/len(inline_bytes):.1f}%)")

    parts = [
        "// Auto-generated by tools/embed_www.py — DO NOT EDIT",
        "// v2.3-final-gz: INDEX_HTML_GZ 은 inline HTML 의 gzip 사전 압축본.",
        "//               응답 시 Content-Encoding: gzip + 단일 httpd_resp_send.",
        "//               STYLE_CSS / APP_JS 는 raw 유지 (디버깅용 직접 GET 가능).",
        '#include "embedded_assets.h"',
        "",
        to_byte_array_cpp("INDEX_HTML_GZ", gz),
        "",
    ]

    # raw string for CSS / JS (직접 GET 디버깅 용도)
    DELIM = "RDT"
    for sym, content in [("STYLE_CSS", css_raw), ("APP_JS", js_raw)]:
        parts.append(f'const char {sym}[] PROGMEM = R"{DELIM}({content}){DELIM}";')
        parts.append("")

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(parts))
    print(f"wrote {OUT}")

if __name__ == "__main__":
    main()
