// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: 2432_1

#include "../ui.h"

void ui_ScreenDevice_screen_init(void)
{
    ui_ScreenDevice = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenDevice, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_ScreenDevice, LV_SCROLLBAR_MODE_OFF);

    ui_Label16 = lv_label_create(ui_ScreenDevice);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 0);
    lv_obj_set_y(ui_Label16, -127);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "장치 설정");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_nanumB20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSaveID = lv_btn_create(ui_ScreenDevice);
    lv_obj_set_width(ui_btnSaveID, 80);
    lv_obj_set_height(ui_btnSaveID, 35);
    lv_obj_set_x(ui_btnSaveID, 50);
    lv_obj_set_y(ui_btnSaveID, 40);
    lv_obj_set_align(ui_btnSaveID, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSaveID, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnSaveID, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnSaveID, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSaveID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_btnSaveID);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 0);
    lv_obj_set_y(ui_Label19, 2);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "저장");
    lv_obj_set_style_text_font(ui_Label19, &ui_font_nanumB15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnLoadMqtt = lv_btn_create(ui_ScreenDevice);
    lv_obj_set_width(ui_btnLoadMqtt, 80);
    lv_obj_set_height(ui_btnLoadMqtt, 35);
    lv_obj_set_x(ui_btnLoadMqtt, 57);
    lv_obj_set_y(ui_btnLoadMqtt, 90);
    lv_obj_set_align(ui_btnLoadMqtt, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnLoadMqtt, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnLoadMqtt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnLoadMqtt, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnLoadMqtt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_btnLoadMqtt);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 0);
    lv_obj_set_y(ui_Label18, 2);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "불러오기");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_nanumB15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_ScreenDevice);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -50);
    lv_obj_set_y(ui_Label20, 90);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "MQTT info  Config");

    ui_Label22 = lv_label_create(ui_ScreenDevice);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -50);
    lv_obj_set_y(ui_Label22, 130);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "UI Images Config");

    ui_btnLoadImages = lv_btn_create(ui_ScreenDevice);
    lv_obj_set_width(ui_btnLoadImages, 80);
    lv_obj_set_height(ui_btnLoadImages, 35);
    lv_obj_set_x(ui_btnLoadImages, 58);
    lv_obj_set_y(ui_btnLoadImages, 130);
    lv_obj_set_align(ui_btnLoadImages, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnLoadImages, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnLoadImages, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnLoadImages, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnLoadImages, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_btnLoadImages);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 0);
    lv_obj_set_y(ui_Label21, 2);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "불러오기");
    lv_obj_set_style_text_font(ui_Label21, &ui_font_nanumB15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ibtnWifi2 = lv_imgbtn_create(ui_ScreenDevice);
    lv_imgbtn_set_src(ui_ibtnWifi2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_ethernet_png, NULL);
    lv_obj_set_width(ui_ibtnWifi2, 32);
    lv_obj_set_height(ui_ibtnWifi2, 15);
    lv_obj_set_x(ui_ibtnWifi2, 90);
    lv_obj_set_y(ui_ibtnWifi2, -127);
    lv_obj_set_align(ui_ibtnWifi2, LV_ALIGN_CENTER);

    ui_btnReboot = lv_btn_create(ui_ScreenDevice);
    lv_obj_set_width(ui_btnReboot, 80);
    lv_obj_set_height(ui_btnReboot, 35);
    lv_obj_set_x(ui_btnReboot, -50);
    lv_obj_set_y(ui_btnReboot, 40);
    lv_obj_set_align(ui_btnReboot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnReboot, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnReboot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnReboot, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnReboot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_btnReboot);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 0);
    lv_obj_set_y(ui_Label23, 2);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "재시작");
    lv_obj_set_style_text_font(ui_Label23, &ui_font_nanumB15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard3 = lv_keyboard_create(ui_ScreenDevice);
    lv_obj_set_width(ui_Keyboard3, 240);
    lv_obj_set_height(ui_Keyboard3, 120);
    lv_obj_set_align(ui_Keyboard3, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Panel2 = lv_obj_create(ui_ScreenDevice);
    lv_obj_set_width(ui_Panel2, 240);
    lv_obj_set_height(ui_Panel2, 120);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, 55);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label17, "Device ID :");

    ui_txtaDeviceID = lv_textarea_create(ui_Panel2);
    lv_obj_set_width(ui_txtaDeviceID, 130);
    lv_obj_set_height(ui_txtaDeviceID, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_txtaDeviceID, 80);
    lv_obj_set_y(ui_txtaDeviceID, -10);
    lv_textarea_set_one_line(ui_txtaDeviceID, true);



    ui_Label15 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 0);
    lv_obj_set_y(ui_Label15, 40);
    lv_label_set_text(ui_Label15, "Home url :");

    ui_txtaServerurl = lv_textarea_create(ui_Panel2);
    lv_obj_set_width(ui_txtaServerurl, 130);
    lv_obj_set_height(ui_txtaServerurl, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_txtaServerurl, 80);
    lv_obj_set_y(ui_txtaServerurl, 30);
    lv_textarea_set_one_line(ui_txtaServerurl, true);



    ui_Label24 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 6);
    lv_obj_set_y(ui_Label24, 80);
    lv_label_set_text(ui_Label24, "Sleep In :");

    ui_Label25 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -5);
    lv_obj_set_y(ui_Label25, 120);
    lv_label_set_text(ui_Label25, "Reboot Time:");

    ui_dropSleep = lv_dropdown_create(ui_Panel2);
    lv_dropdown_set_options(ui_dropSleep, "No\n1\n2\n3\n4\n5\n10\n20\n30\n60");
    lv_obj_set_width(ui_dropSleep, 80);
    lv_obj_set_height(ui_dropSleep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dropSleep, 80);
    lv_obj_set_y(ui_dropSleep, 70);
    lv_obj_add_flag(ui_dropSleep, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Label26 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 170);
    lv_obj_set_y(ui_Label26, 80);
    lv_label_set_text(ui_Label26, "/Min");

    ui_dropReboot = lv_dropdown_create(ui_Panel2);
    lv_dropdown_set_options(ui_dropReboot, "No\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11");
    lv_obj_set_width(ui_dropReboot, 80);
    lv_obj_set_height(ui_dropReboot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dropReboot, 97);
    lv_obj_set_y(ui_dropReboot, 110);
    lv_obj_add_flag(ui_dropReboot, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Label27 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 181);
    lv_obj_set_y(ui_Label27, 120);
    lv_label_set_text(ui_Label27, "/HH");

    lv_obj_add_event_cb(ui_btnSaveID, ui_event_btnSaveID, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnLoadMqtt, ui_event_btnLoadMqtt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnLoadImages, ui_event_btnLoadImages, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ibtnWifi2, ui_event_ibtnWifi2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnReboot, ui_event_btnReboot, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtaDeviceID, ui_event_txtaDeviceID, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtaServerurl, ui_event_txtaServerurl, LV_EVENT_ALL, NULL);

}
