// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: 2432_1

#include "../ui.h"

void ui_ScreenWifi_screen_init(void)
{
    ui_ScreenWifi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_ScreenWifi);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -127);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "WIFI 설정");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_nanumB20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dropSSID = lv_dropdown_create(ui_ScreenWifi);
    lv_dropdown_set_options(ui_dropSSID, "");
    lv_obj_set_width(ui_dropSSID, 161);
    lv_obj_set_height(ui_dropSSID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dropSSID, 22);
    lv_obj_set_y(ui_dropSSID, -80);
    lv_obj_set_align(ui_dropSSID, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dropSSID, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_txtaPassword = lv_textarea_create(ui_ScreenWifi);
    lv_obj_set_width(ui_txtaPassword, 80);
    lv_obj_set_height(ui_txtaPassword, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_txtaPassword, 13);
    lv_obj_set_y(ui_txtaPassword, -30);
    lv_obj_set_align(ui_txtaPassword, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(ui_txtaPassword, true);
    lv_textarea_set_password_mode(ui_txtaPassword, true);



    ui_Label4 = lv_label_create(ui_ScreenWifi);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -90);
    lv_obj_set_y(ui_Label4, -80);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "SSID :");

    ui_Label5 = lv_label_create(ui_ScreenWifi);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -72);
    lv_obj_set_y(ui_Label5, -30);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Password :");

    ui_btnSerch = lv_btn_create(ui_ScreenWifi);
    lv_obj_set_width(ui_btnSerch, 80);
    lv_obj_set_height(ui_btnSerch, 35);
    lv_obj_set_x(ui_btnSerch, -50);
    lv_obj_set_y(ui_btnSerch, 15);
    lv_obj_set_align(ui_btnSerch, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSerch, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnSerch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnSerch, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSerch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_btnSerch);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 2);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "검색");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_nanumB15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnWifiConn = lv_btn_create(ui_ScreenWifi);
    lv_obj_set_width(ui_btnWifiConn, 80);
    lv_obj_set_height(ui_btnWifiConn, 35);
    lv_obj_set_x(ui_btnWifiConn, 50);
    lv_obj_set_y(ui_btnWifiConn, 15);
    lv_obj_set_align(ui_btnWifiConn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnWifiConn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnWifiConn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_btnWifiConn);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, 2);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "연결");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_nanumB15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ibtnEthernet = lv_imgbtn_create(ui_ScreenWifi);
    lv_imgbtn_set_src(ui_ibtnEthernet, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_ethernet_png, NULL);
    lv_obj_set_width(ui_ibtnEthernet, 32);
    lv_obj_set_height(ui_ibtnEthernet, 15);
    lv_obj_set_x(ui_ibtnEthernet, 90);
    lv_obj_set_y(ui_ibtnEthernet, -127);
    lv_obj_set_align(ui_ibtnEthernet, LV_ALIGN_CENTER);

    ui_chkLookPass = lv_checkbox_create(ui_ScreenWifi);
    lv_checkbox_set_text(ui_chkLookPass, "See");
    lv_obj_set_width(ui_chkLookPass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chkLookPass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chkLookPass, 88);
    lv_obj_set_y(ui_chkLookPass, -30);
    lv_obj_set_align(ui_chkLookPass, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chkLookPass, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_ibtnDevice = lv_imgbtn_create(ui_ScreenWifi);
    lv_imgbtn_set_src(ui_ibtnDevice, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_set_png, NULL);
    lv_obj_set_width(ui_ibtnDevice, 32);
    lv_obj_set_height(ui_ibtnDevice, 15);
    lv_obj_set_x(ui_ibtnDevice, -90);
    lv_obj_set_y(ui_ibtnDevice, -127);
    lv_obj_set_align(ui_ibtnDevice, LV_ALIGN_CENTER);

    ui_Keyboard1 = lv_keyboard_create(ui_ScreenWifi);
    lv_obj_set_width(ui_Keyboard1, 240);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_txtaPassword, ui_event_txtaPassword, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSerch, ui_event_btnSerch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnWifiConn, ui_event_btnWifiConn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ibtnEthernet, ui_event_ibtnEthernet, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_chkLookPass, ui_event_chkLookPass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ibtnDevice, ui_event_ibtnDevice, LV_EVENT_ALL, NULL);

}
