// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: 2432_1

#include "../ui.h"

void ui_ScreenEthernet_screen_init(void)
{
    ui_ScreenEthernet = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenEthernet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_ScreenEthernet);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, -127);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "이더넷 설정");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_nanumB20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ibtnWifi = lv_imgbtn_create(ui_ScreenEthernet);
    lv_imgbtn_set_src(ui_ibtnWifi, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_set_png, NULL);
    lv_obj_set_width(ui_ibtnWifi, 32);
    lv_obj_set_height(ui_ibtnWifi, 15);
    lv_obj_set_x(ui_ibtnWifi, -90);
    lv_obj_set_y(ui_ibtnWifi, -127);
    lv_obj_set_align(ui_ibtnWifi, LV_ALIGN_CENTER);

    ui_Panel1 = lv_obj_create(ui_ScreenEthernet);
    lv_obj_set_width(ui_Panel1, 240);
    lv_obj_set_height(ui_Panel1, 270);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 30);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_Panel1, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -150);
    lv_obj_set_y(ui_Label9, -70);
    lv_obj_set_align(ui_Label9, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label9, "IP :");

    ui_Label10 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -150);
    lv_obj_set_y(ui_Label10, -30);
    lv_obj_set_align(ui_Label10, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label10, "Subnet :");

    ui_Label11 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -150);
    lv_obj_set_y(ui_Label11, 10);
    lv_obj_set_align(ui_Label11, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label11, "Gateway :");

    ui_Label13 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -150);
    lv_obj_set_y(ui_Label13, 90);
    lv_obj_set_align(ui_Label13, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label13, "Se-DNS :");

    ui_Label12 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -150);
    lv_obj_set_y(ui_Label12, 50);
    lv_obj_set_align(ui_Label12, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label12, "Pri-DNS :");

    ui_Label1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -150);
    lv_obj_set_y(ui_Label1, -110);
    lv_obj_set_align(ui_Label1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label1, "DHCP :");

    ui_chkDhcp = lv_checkbox_create(ui_Panel1);
    lv_checkbox_set_text(ui_chkDhcp, "DHCP 사용");
    lv_obj_set_width(ui_chkDhcp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chkDhcp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chkDhcp, 16);
    lv_obj_set_y(ui_chkDhcp, -110);
    lv_obj_set_align(ui_chkDhcp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chkDhcp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_chkDhcp, &ui_font_nanumB15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtaIp = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_txtaIp, 130);
    lv_obj_set_height(ui_txtaIp, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_txtaIp, 38);
    lv_obj_set_y(ui_txtaIp, -70);
    lv_obj_set_align(ui_txtaIp, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(ui_txtaIp, true);



    ui_txtaSubnet = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_txtaSubnet, 130);
    lv_obj_set_height(ui_txtaSubnet, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_txtaSubnet, 38);
    lv_obj_set_y(ui_txtaSubnet, -30);
    lv_obj_set_align(ui_txtaSubnet, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(ui_txtaSubnet, true);



    ui_txtaGateway = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_txtaGateway, 130);
    lv_obj_set_height(ui_txtaGateway, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_txtaGateway, 38);
    lv_obj_set_y(ui_txtaGateway, 10);
    lv_obj_set_align(ui_txtaGateway, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(ui_txtaGateway, true);



    ui_txtaPriDns = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_txtaPriDns, 130);
    lv_obj_set_height(ui_txtaPriDns, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_txtaPriDns, 38);
    lv_obj_set_y(ui_txtaPriDns, 50);
    lv_obj_set_align(ui_txtaPriDns, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(ui_txtaPriDns, true);



    ui_txtaSeDns = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_txtaSeDns, 130);
    lv_obj_set_height(ui_txtaSeDns, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_txtaSeDns, 38);
    lv_obj_set_y(ui_txtaSeDns, 90);
    lv_obj_set_align(ui_txtaSeDns, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(ui_txtaSeDns, true);



    ui_btnEthernetConn = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_btnEthernetConn, 80);
    lv_obj_set_height(ui_btnEthernetConn, 30);
    lv_obj_set_x(ui_btnEthernetConn, 0);
    lv_obj_set_y(ui_btnEthernetConn, 140);
    lv_obj_set_align(ui_btnEthernetConn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnEthernetConn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnEthernetConn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_btnEthernetConn);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "연결");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_nanumB15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 280);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "*정보를 입력하고 연결을 누르세요.");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_nanumB15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard2 = lv_keyboard_create(ui_ScreenEthernet);
    lv_obj_set_width(ui_Keyboard2, 240);
    lv_obj_set_height(ui_Keyboard2, 130);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_ibtnWifi, ui_event_ibtnWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_chkDhcp, ui_event_chkDhcp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtaIp, ui_event_txtaIp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtaSubnet, ui_event_txtaSubnet, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtaGateway, ui_event_txtaGateway, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtaPriDns, ui_event_txtaPriDns, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtaSeDns, ui_event_txtaSeDns, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnEthernetConn, ui_event_btnEthernetConn, LV_EVENT_ALL, NULL);

}
