// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: 2432_1

#include "../ui.h"

void ui_ScreenMain_screen_init(void)
{
    ui_ScreenMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImagePhoto = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_ImagePhoto, &ui_img_photo_png);
    lv_obj_set_width(ui_ImagePhoto, 100);
    lv_obj_set_height(ui_ImagePhoto, 150);
    lv_obj_set_x(ui_ImagePhoto, 0);
    lv_obj_set_y(ui_ImagePhoto, 86);
    lv_obj_add_flag(ui_ImagePhoto, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagePhoto, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageName = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_ImageName, &ui_img_name_png);
    lv_obj_set_width(ui_ImageName, 240);
    lv_obj_set_height(ui_ImageName, 84);
    lv_obj_set_x(ui_ImageName, 0);
    lv_obj_set_y(ui_ImageName, 236);
    lv_obj_add_flag(ui_ImageName, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageName, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ibtnLogo = lv_imgbtn_create(ui_ScreenMain);
    lv_imgbtn_set_src(ui_ibtnLogo, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_title_png, NULL);
    lv_obj_set_width(ui_ibtnLogo, 240);
    lv_obj_set_height(ui_ibtnLogo, 86);

    ui_ImageIn = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_ImageIn, &ui_img_in_png);
    lv_obj_set_width(ui_ImageIn, 140);
    lv_obj_set_height(ui_ImageIn, 150);
    lv_obj_set_x(ui_ImageIn, 100);
    lv_obj_set_y(ui_ImageIn, 86);
    lv_obj_add_flag(ui_ImageIn, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageIn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageOut = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_ImageOut, &ui_img_out_png);
    lv_obj_set_width(ui_ImageOut, 140);
    lv_obj_set_height(ui_ImageOut, 150);
    lv_obj_set_x(ui_ImageOut, 100);
    lv_obj_set_y(ui_ImageOut, 86);
    lv_obj_add_flag(ui_ImageOut, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageOut, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ibtnRoom = lv_imgbtn_create(ui_ScreenMain);
    lv_imgbtn_set_src(ui_ibtnRoom, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_out_png, NULL);
    lv_obj_set_width(ui_ibtnRoom, 140);
    lv_obj_set_height(ui_ibtnRoom, 150);
    lv_obj_set_x(ui_ibtnRoom, 100);
    lv_obj_set_y(ui_ibtnRoom, 86);

    lv_obj_add_event_cb(ui_ibtnLogo, ui_event_ibtnLogo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ibtnRoom, ui_event_ibtnRoom, LV_EVENT_ALL, NULL);

}
